### ISSUE TITLE
is it possible to allow docker container to run as non root user

### ISSUE THREAD

**Issue by haai** [JetBrains/teamcity-docker-server#22]
trying to deploy a teamcity server image in openshift fails and the stdout logs a message like
```
* [WARNING] Image "teamcity-server" runs as the 'root' user which may not be permitted by your cluster administrator
```
Is it possible to change the teamcity server image that it runs as non root per default so that it could be deployed in an openshift context?

**Comment by kir** [comment]
Does openshift allow specifying userId to run the container with? Basically, teamcity-server image does not allow running under root, so it should be possible.
If it is not possible, please create a corresponding issue in [TeamCity issue tracker](https://youtrack.jetbrains.com/issues/TW)

Thanks!

**Comment by kir** [comment]
Thank you, I've create a corresponding issue: https://youtrack.jetbrains.com/issue/TW-58967, please vote/watch there.

**Comment by claco** [comment]
Came here looking for/to ask for the same thing. Even something as simple as what the Artifactory Docker does with a pre created uid/guid that you can override back to 0:0 if you have too in Docker.

https://www.jfrog.com/confluence/display/RTF/Installing+with+Docker

**Comment by rv4Flyver** [comment]
It is possible to use non-root, the only problem is that uid:gid should be 1000:1000 as `/opt/teamcity` belongs to `uid=1000(tcuser) gid=1000(tcuser) groups=1000(tcuser)`

**Comment by WilliamStam** [comment]
the 1000 is hard coded into the app/setup. a few hours later and we're minus a ton of hair now. even made the youngsters old. why o why jetbrains hard code something like that in :( 

so basically run docker as root (sudo) or run container as root (--user 0)? 

there HAS to be a way??

```yaml
services:
    teamcity:
        user: ${USER_UID}:${USER_GID}
        image: jetbrains/teamcity-server:latest
        container_name: teamcity
        hostname: teamcity
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - ./data:/data/teamcity_server/datadir
            - $ROOT/logs/teamcity:/opt/teamcity/logs
        environment:
            - TEAMCITY_SERVER_MEM_OPTS="-Xmx4g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=640m"
            - TEAMCITY_HTTPS_PROXY_ENABLED=true
        networks:
            internal:
```

the user that runs docker is part of a group and that user and group own the folders that get written to. the id's arent 1000 tho. so hack and slash if you _cant_ run docker as root is to then go to the users with uid 1000 and group 1000 and rename them and use those? -_- - sorry frustrated at the moment

many many years later...
