### ISSUE TITLE
Increase RAM for TeamCity with TEAMCITY_SERVER_MEM_OPTS

### ISSUE THREAD

**Issue by florianbaer** [JetBrains/teamcity-docker-server#33]
Hi all

We have currently a DockerSwarm containing a service for our TeamCity.

Our teamcity.yml looks like this:
```
version: '3.3'

services:
  server:
    image: jetbrains/teamcity-server
    volumes:
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-logs:/opt/teamcity/logs
    networks:
      - traefik-public
        #    environment:
        #      - TEAMCITY_SERVER_MEM_OPTS="-Xms512m -Xmx2048m -XX:PermSize=250m -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.portainer.portainer-data == true
      labels:
        - traefik.frontend.rule=Host:teamcity.${DOMAIN}
        - traefik.enable=true
        - traefik.port=8111
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

networks:
  traefik-public:
    external: true

volumes:
  teamcity-data:
  teamcity-logs
```

When i uncomment and set the TEAMCITY_SERVER_MEM_OPTS as the following:
`TEAMCITY_SERVER_MEM_OPTS="-Xms512m -Xmx2048m -XX:PermSize=250m -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"`
or the following 
`TEAMCITY_SERVER_MEM_OPTS="-Xmx2048m -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"`
then the service log shows me the following log output.
```
Invalid initial heap size: -Xms512m -Xmx2048m -XX:PermSize=250m -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Running on this Docker Version:
```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

It's running on a Ubuntu docker host: 
```
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.15.0-48-generic
Uptime: 5d 18h 6m
Packages: 525
Shell: bash 4.4.19
CPU: AMD EPYC 7551 32-Core @ 2x 1.996GHz
GPU: svgadrmfb
RAM: 1981MiB / 3945MiB
```
